### ISSUE TITLE
Server failure at resolver

### ISSUE THREAD

**Issue by liuxyon** [oocx/acme.net#1]
I am try install in IIS8.5. why show wrong ? How I do it?

using server https://acme-v01.api.letsencrypt.org/
trying to create new registration
error:
urn:acme:error:malformed
Error creating new registration :: Validation of contact mailto:host@ongod.org f
ailed: Server failure at resolver

**Comment by oocx** [comment]
I can't reproduce the problem. Which command line arguments did you use exactly?

**Comment by liuxyon** [comment]
I just only use ongod.org email address not work. change to other domain email address is work. I don't know it is why.

**Comment by liuxyon** [comment]
by the way, How to automatically renew certificates?

**Comment by oocx** [comment]
It looks like the ACME server does not accept that email address. If you need to register with that address, you could ask for help on the official Let's Encrypt support forums: https://community.letsencrypt.org/

I have not added any auto renewal features yet. I will probably add auto renewal support in a future version if it annoys me too much that I have to manually renew my own SSL certificates.
