### ISSUE TITLE
.net 461 Parameter parsing fails

### ISSUE THREAD

**Issue by FrankPfattheicher** [oocx/acme.net#23]
The parameter IEnumerable<string> Domains could not be parsed.

Type conversion error :-(

**Comment by iamcarbon** [comment]
Is this using the NuGet package or from this branch?

Can you provide a stack trace?

**Comment by FrankPfattheicher** [comment]
To reproduce use the following command line arguments:
`
-d domain1.com -v Verbose -p 123456 -a -i iis -w domain1 -m mailto:info@domain1.de –j
`
Just start debugging Oocx.ACME.Console using VS2017
The following line will fail
`
parser.ParseArguments(args, options);
`
System.InvalidCastException: 'Ungültige Umwandlung von "System.String" in "System.Collections.Generic.IEnumerable`1[[System.String, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]]".'
(Sorry for german message text)

Need more ?

**Comment by FrankPfattheicher** [comment]
obsolete
